Add CircleCI config

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -5,24 +5,31 @@ jobs:
       - run: echo "This is a build step"    # similar to "script" in GitLab
 
   test:
-     bundler-audit:
-       machine: true
-       steps:
-         - checkout
+    steps:
+      - checkout
+      - run: echo "This is a test step"
 
-         - run: docker run --rm -v $(pwd):/src -w /src hysnsec/bundle-audit check --format json --output bundle-audit-output.json
+  bundler-audit:
+    machine: true
+    steps:
+      - checkout
 
-         - store_artifacts:
-             path: bundle-audit-output.json
-             destination: bundler-audit-artifact
+      - run: 
+          command: docker run --rm -v $(pwd):/src -w /src hysnsec/bundle-audit check --format json --output bundle-audit-output.json || true
+
+      - store_artifacts:
+          path: bundle-audit-output.json
+          destination: bundler-audit-artifact
+          when: always
 
   integration:
     steps:
       - checkout
       - run:
           command: |
-            echo "This is an integration step
+            echo "This is an integration step"
             exit 1
+          when: always                    # Even if the job fails, continue to the next stages
 
   prod:
     steps:
@@ -37,7 +44,7 @@ workflows:
       - test:
           requires:
             - build
-      - bundler-audit
+      - bundler-audit:
           requires:
             - test
       - integration:
